package com.machfour.macros.names

// codenames - for use with CSV import
const val QUANTITY_NAME = "quantity"
const val ENERGY_NAME = "energy"
const val PROTEIN_NAME = "protein"
const val FAT_NAME = "fat"
const val SATURATED_FAT_NAME = "saturated_fat"
const val CARBOHYDRATE_NAME = "carbohydrate"
const val SUGAR_NAME = "sugar"
const val FIBRE_NAME = "fibre"
const val SODIUM_NAME = "sodium"
const val POTASSIUM_NAME = "potassium"
const val CALCIUM_NAME = "calcium"
const val IRON_NAME = "iron"
const val MONOUNSATURATED_FAT_NAME = "monounsaturated_fat"
const val POLYUNSATURATED_FAT_NAME = "polyunsaturated_fat"
const val OMEGA_3_FAT_NAME = "omega_3"
const val OMEGA_6_FAT_NAME = "omega_6"
const val STARCH_NAME = "starch"
const val SALT_NAME = "salt"
const val WATER_NAME = "water"
const val CARBOHYDRATE_BY_DIFF_NAME = "carbohydrate_by_diff"
const val ALCOHOL_NAME = "alcohol"
const val SUGAR_ALCOHOL_NAME = "sugar_alcohol"
const val CAFFEINE_NAME = "caffeine"

const val QUANTITY_UNIT_NAME = "quantity_unit"
const val ENERGY_UNIT_NAME = "energy_unit"
