#!/bin/sh

MACROS_VERSION="1.0-SNAPSHOT"


DEVEL_DIR="/home/max/devel/macros"
JAR_DIR="${DEVEL_DIR}/build/libs"
JAR_FILE="macros-${MACROS_VERSION}.jar"
JAR_PATH="${JAR_DIR}/${JAR_FILE}"


#PROFILE="-agentpath:/opt/yourkit/bin/linux-x86-64/libyjpagent.so=exceptions=disable,delay=10000"
# AOT things
#"-XX:+PrintAOT"
#java -XX:AOTLibrary=${DEVEL_DIR}/macros.so:${DEVEL_DIR}/macros-libs.so -enableassertions -cp "$CLASSPATH" ${MAINCLASS} "$@"

# show class loading timing:
# -verbose:class 

# log touched methods for use with AOT
#     -XX:+UnlockDiagnosticVMOptions \
#     -XX:+LogTouchedMethods \
#     -XX:+PrintTouchedMethodsAtExit 

unset _JAVA_OPTIONS

#archlinux-java-run --min 14 -- -jar build/libs/macros-1.0-SNAPSHOT.jar

archlinux-java-run --min 14 -- -enableassertions \
    -XX:+UnlockExperimentalVMOptions \
    -XX:AOTLibrary=${DEVEL_DIR}/macros-touched-methods.so \
	-jar "$JAR_PATH" "$@"
