#!/bin/sh

unset _JAVA_OPTIONS
CLASSPATH="/home/max/devel/macros-java/out/production/macros-java/:/home/max/devel/macros-java/lib/super-csv-2.4.0.jar:/home/max/devel/macros-java/lib/sqlite-jdbc-3.23.1.jar"
PROFILE="-agentpath:/opt/yourkit/bin/linux-x86-64/libyjpagent.so=exceptions=disable,delay=10000"
java -enableassertions -cp "$CLASSPATH" com.machfour.macros.cli.CliMain "$@"
